ARTICLE_SLUG_MAX_LENGTH = 255
ARTICLE_SLUG_MIN_LENGTH = 2
ARTICLE_TITLE_MAX_LENGTH = 255
ARTICLE_TITLE_MIN_LENGTH = 2
DESCRIPTION_MAX_LENGTH = 10000
DESCRIPTION_MIN_LENGTH = 2
CONTENT_MAX_LENGTH = 65535
CONTENT_MIN_LENGTH = 2
