# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170415_1407'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileUpload',
            new_name='File',
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_file', to='posts.File'),
        ),
    ]
