# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20170523_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, default='Lorem Ipsum', max_length=255),
            preserve_default=False,
        ),
    ]
