# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20170526_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='size',
            new_name='file_size',
        ),
        migrations.AddField(
            model_name='file',
            name='file_path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
