# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20170706_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='liked',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='profiles.Profile'),
        ),
    ]
