# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20170713_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='name',
            new_name='file_name',
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_file', to='core.S3FileUpload'),
        ),
    ]
