# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20170831_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_file', to='posts.FileUpload'),
        ),
    ]
