# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170605_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodel',
            name='api_root',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='app_version',
            field=models.CharField(default='1.0.0', max_length=8),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='media_root',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='static_root',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
