# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170705_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='S3FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(help_text='Name of the file with which user uploaded', max_length=255, verbose_name='File name ')),
                ('file_size', models.BigIntegerField(help_text='Size of the file in bytes', verbose_name='File size')),
                ('file_type', models.CharField(help_text='Type of file content', max_length=5, verbose_name='File type')),
                ('file_content_type', models.CharField(help_text='Content type of file', max_length=20, verbose_name='File content type')),
                ('key', models.CharField(help_text='Key of the file being uploaded', max_length=255, verbose_name='Key')),
                ('last_modified', models.DateTimeField(help_text='Last Modified Date', verbose_name='Last Modified')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
