# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-13 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170413_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='activation_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='activation_key_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
