# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-13 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170413_1544'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountProfile',
            new_name='Profile',
        ),
    ]
