# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_oauthaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthaccount',
            name='user',
        ),
        migrations.DeleteModel(
            name='OauthAccount',
        ),
    ]
