# Generated by Django 6.0.6 on 2026-06-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0003_alter_tag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
