language: # => 1
  - python

python:# => 2
  # - 2.7
  # - 3.6

services:# => 3
  # - mysql

env: # => 4
# - DJANGO="x.y.z"

install:# => 5
  # - pip install -r requirements.txt

before_script:
  # - python manage.py migrate
