# Generated by Django 6.0.6 on 2026-06-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("app_version", models.CharField(default="0.0.1", max_length=20)),
                ("min_supported_version", models.CharField(blank=True, max_length=20)),
                ("force_update", models.BooleanField(default=False)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("maintenance_message", models.TextField(blank=True)),
                ("feature_flags", models.JSONField(blank=True, default=dict)),
                ("api_base_url", models.URLField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
