# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_version', models.CharField(default=b'1.0.0', max_length=8)),
                ('api_url', models.CharField(blank=True, default=b'', max_length=255)),
                ('static_root', models.CharField(blank=True, default=b'', max_length=255)),
                ('media_root', models.CharField(blank=True, default=b'', max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
