# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appmodel',
            old_name='api_url',
            new_name='api_root',
        ),
    ]
