# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20170526_1356'),
        ('profiles', '0005_auto_20170526_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to='posts.File'),
        ),
    ]
