# Generated by Django 6.0.6 on 2026-06-21 11:40

import django.db.models.deletion
import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
        ("tags", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(max_length=10000)),
                ("content", django_mysql.models.SizedTextField(size_class=4)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="articles",
                        to="profiles.profile",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(related_name="article_tags", to="tags.tag"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
