# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20170627_1228'),
        ('articles', '0008_auto_20170707_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('liked', models.NullBooleanField(default=None)),
                ('article_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comment_likes', to='articles.ArticleComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comment_likes', to='profiles.Profile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='articlecommentlike',
            unique_together=set([('user', 'article_comment')]),
        ),
    ]
