# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-05 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20170726_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecommentlike',
            name='article_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comment_likes', to='articles.ArticleComment'),
        ),
        migrations.AlterField(
            model_name='articlecommentlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comment_likes', to='profiles.Profile'),
        ),
    ]
