# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-14 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170414_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='activation_key',
            new_name='security_key',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='activation_key_expires',
            new_name='security_key_expires',
        ),
    ]
