# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='articlecomment',
            old_name='author',
            new_name='user',
        ),
    ]
