AUDIO_POST_URL_MAX_LENGTH = 2000
AUDIO_POST_SLUG_MAX_LENGTH = 255
AUDIO_POST_TITLE_MAX_LENGTH = 255
AUDIO_POST_TITLE_MIN_LENGTH = 5
AUDIO_POST_DESCRIPTION_MAX_LENGTH = 1000
AUDIO_POST_DESCRIPTION_MIN_LENGTH = 5

AUDIO_OUTPUT_FORMAT_MP3 = "mp3"
AUDIO_OUTPUT_FORMAT_OGG = "ogg_vorbis"
AUDIO_OUTPUT_FORMAT_PCM = "pcm"
AUDIO_OUTPUT_FORMAT_CHOICES = (
    (AUDIO_OUTPUT_FORMAT_MP3, "mp3"),
    (AUDIO_OUTPUT_FORMAT_OGG, "ogg_vorbis"),
    (AUDIO_OUTPUT_FORMAT_PCM, "pcm"),
)

AUDIO_STATUS_PENDING = "pending"
AUDIO_STATUS_SUCCESS = "success"
AUDIO_STATUS_FAILED = "failed"
AUDIO_STATUS_CHOICES = (
    (AUDIO_STATUS_PENDING, "Pending"),
    (AUDIO_STATUS_SUCCESS, "Success"),
    (AUDIO_STATUS_FAILED, "Failed"),
)
