# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_postlikes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostLikes',
            new_name='PostLike',
        ),
    ]
