# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20170828_0828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='FileUpload',
        ),
    ]
