# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-02 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20170905_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_file', to='files.FileUpload'),
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
