# Generated by Django 6.0.6 on 2026-09-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio_articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audioarticle",
            name="audio_file",
            field=models.URLField(max_length=2000),
        ),
    ]
