# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-02 13:14
from __future__ import unicode_literals

import apps.files.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0009_auto_20170905_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=255, upload_to=apps.files.models.file_path_fn)),
                ('file_name', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=5)),
                ('file_content_type', models.CharField(max_length=20)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_path', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='profiles.Profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
